// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    GameControls: typeof import('./components/GameControls.vue')['default']
    LocalGame: typeof import('./components/LocalGame.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RemoateGameStatus: typeof import('./components/RemoateGameStatus.vue')['default']
    RemoteGame: typeof import('./components/RemoteGame.vue')['default']
    Scrim: typeof import('./components/Scrim.vue')['default']
    Sharing: typeof import('./components/Sharing.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Tile: typeof import('./components/Tile.vue')['default']
  }
}

export {}
