// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    CopyLink: typeof import('./components/CopyLink.vue')['default']
    GameControls: typeof import('./components/GameControls.vue')['default']
    LocalGame: typeof import('./components/LocalGame.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RemoteGame: typeof import('./components/RemoteGame.vue')['default']
    RemoteGameSmall: typeof import('./components/RemoteGameSmall.vue')['default']
    RemoteGameStatus: typeof import('./components/RemoteGameStatus.vue')['default']
    Scrim: typeof import('./components/Scrim.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Tile: typeof import('./components/Tile.vue')['default']
  }
}
